### PR TITLE
change: Update project target frameworks and dependencies

### LINKED ISSUE #264: conflict between FirebaseAdmin 1.17.1 and Google.Cloud.Firestore 2.2.0
there is a conflict arises when I include both `FirebaseAdmin 1.17.1` and `Google.Cloud.Firestore 2.2.0` packages.

`FirebaseAdmin 1.17.1` package has a dependency on `Google.Api.Gax 2.7.0`.
`Google.Cloud.Firestore 2.2.0` package has a dependency on `Google.Api.Gax 3.2.0`.

When installing both packages side by side in one .Net project, the `FirebaseAdmin 1.17.1` automatically grabs the higher version `Google.Api.Gax 3.2.0` which causes compile errors. specifically because the use of `Microsoft.Bcl.AsyncInterfaces` in `Google.Api.Gax 3.2.0` while using `System.Interactive.Async` in `Google.Api.Gax 2.7.0`

I guess this issue belongs here because `FirebaseAdmin` is not restricting `Google.Api.Gax` dependency to version `2.7.0`

> When installing `FirebaseAdmin 1.17.1` solely.
google api gax

> When installing both packages
google api gax_together

### PR DESCRIPTION
**Pull request by DenSmoke**
- Project target frameworks replaced with .NET Framework 4.6.1 and .NET Standard 2.0 to be consistent with the frameworks supported by other .NET libraries associated with Google Cloud Platform.
- Removed Google.Api.Gax
- Updated Google.Api.Gax.Rest to 3.2.0
- Updated Google.Apis.Auth to 1.49.0
- Updated System.Collections.Immutable to 1.7.1
- Fixed tests

API CHANGE: Dropped support for `netstandard1.5` and `net45` target frameworks. Developers are now required to use `netstandard2.0` or `net461`.
API CHANGE: Upgraded the dependency `Google.Api.Gax` to the latest major version. Developers that use the [`PagedAsyncEnumerable`](https://googleapis.github.io/google-cloud-dotnet/docs/api/Google.Api.Gax.PagedAsyncEnumerable-2.html) interface from this package (usually as the return value of list iteration API calls), may have to update their implementations accordingly.

Resolves #264 #265 #207

### CODE REVIEW

**Comment by DenSmoke** [comment]
@hiranya911 @lahirumaramba Can someone review please?

**Comment by hiranya911** [comment]
@DenSmoke Thanks for the PR. Really appreciate your effort. This contains several breaking changes. Specifically, following changes are breaking:

1. Dropping support for netstandard1.5
2. Upgrading from Gax 2.0 to 3.0

We can look into accepting those changes in the next quarter, and releasing v2 of the SDK. Can I ask you to extract the above 2 changes from here into a separate PR? The remaining changes in this PR (e.g. upgrading test dependencies) can be merged immediately.

**Comment by DenSmoke** [comment]
@hiranya911 Upgrading test dependencies is not critical. Main purpose is to solve conflicts like in issue #207 when using GAX 3.0 dependent Google Cloud .NET libraries and Firebase Admin SDK in same .NET project

**Comment by hiranya911** [comment]
Yeah, I understand. We can hold on to this PR for now, and come up with a plan to merge it in the coming months.  I just need to sync up with other teams and see if we have any upcoming releases that might potentially conflict with this.

**Comment by hiranya911** [comment]
We have slated this for a release in the next quarter (q4 2020). As a first step we will try to add `net461` to the list of target frameworks without any additional changes, and release that. Then we can merge this PR on top of that.

**Comment by hiranya911** [comment]
@DenSmoke can I ask you to update this PR and sync up with the latest state of the master branch? We can merge this soon after that.

**Comment by DenSmoke** [comment]
@hiranya911 done

**Review by hiranya911 — APPROVED** [review]
Thank you @DenSmoke. This LGTM. I'll merge it in a couple of days, and start working on a release.

**Pull request merged**
