### PR TITLE
Closes #153. Add additional FCM options for Android Notification

### LINKED ISSUE #153: Add latest HTTP v1 options
It seems there are a lot of newer options for FCM not available in the .NET Firebase Admin  (see 
 [https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidNotification](url)).

Specifically the newer options for AndroidNotifications. The current class ends at "channel_id", however the following are now available:

  "ticker": string,
  "sticky": boolean,
  "event_time": string,
  "local_only": boolean,
  "notification_priority": enum (NotificationPriority),
  "default_sound": boolean,
  "default_vibrate_timings": boolean,
  "default_light_settings": boolean,
  "vibrate_timings": [
    string
  ],
  "visibility": enum (Visibility),
  "notification_count": integer,
  "light_settings": {
    object (LightSettings)
  },
  "image": string

Is there any plan to add support for these?

### PR DESCRIPTION
**Pull request by levimatheri**
I couldn't get xUnit to compare `LightSettingsColor` so I assert the properties separately.
Let me know if there's changes I should make.

Thanks!

Related to: #153

### CODE REVIEW

**Comment by lahirumaramba** [comment]
Thank you @levimatheri for the contribution!
There are a few minor changes we have to make in order to match the public API to the internally approved one (for example,`PriorityType` should be renamed to `Priority`). These are minor changes and I can take over from here. As the next step I am merging this PR to a feature branch `fcm-android-notif-param`. I will add integration tests and other minor changes to the API there before merging to the main branch.

**Comment by lahirumaramba** [comment]
@levimatheri I realized that you decided to use `PriorityType` for the `enum` to avoid naming conflicts. Thank you. We might have to revise the internal proposal to reflect this change before releasing the API. I will update the progress here.

**Comment by bigpjo** [comment]
Thank you @levimatheri . @lahirumaramba do you know when this pull request is likely to be merged, this is a fantastic package and it will be great for us to use the localization options available when this is merged

**Comment by lahirumaramba** [comment]
Thank you for your patience! The initial changes required updates to the internally proposed public API. It also required a few changes to the light settings color conversion. I have started #317 to merge all the changes (proposed by @levimatheri Thank you!) to the main branch.

**Comment by lahirumaramba** [comment]
This feature is now available in v2.3.0. Thank you for your contribution!

**Pull request merged**
