### PR TITLE
Add get(by id) and delete user

### PR DESCRIPTION
**Pull request by levimatheri**
Please review my code as I'm new to this project. For the tests, I followed [this API reference](https://firebase.google.com/docs/reference/rest/auth/) but I'm not sure about the DeleteUser test. These additions partly fix [#9](https://github.com/firebase/firebase-admin-dotnet/issues/9). We still need to add GetUser by email and phone number but UserRecord only has uid member.

### CODE REVIEW

**Comment by levimatheri** [comment]
I signed it!

**Comment by hiranya911** [comment]
Thanks @levimatheri. A few high-level feedback points on this:

1. `UserRecord` type also need to be updated to be in sync with other SDKs: https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/auth/UserRecord
2. Eventually, we need to expose the new methods from the `FirebaseAuth` class. But it's ok to do so in a separate pull request, after this one is complete.
3. Check the last message above from the CLA bot. It looks like your CLA was signed for a different email address, than the one used to make GitHub commits?

**Comment by levimatheri** [comment]
@hiranya911 thank you for your review and feedback. Will try and resolve the CLA issue

**Comment by levimatheri** [comment]
@googlebot I signed it!

**Comment by levimatheri** [comment]
Closing this because of the CLA check. Will attempt another PR

**Pull request closed without merging**
